load("@rules_cc//cc:defs.bzl", "cc_library")

filegroup(name="empty")

filegroup(
    name = "clang_tidy_config",
    srcs = [".clang-tidy"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "clang_tidy_analyzer_config",
    srcs = [".clang-tidy"], # Will use same config for now
    visibility = ["//visibility:public"],
)

cc_library(
    name = "zetasketch-cpp",
    srcs = [
        "src/hll/math_utils.cc",
        "src/hll/normal_representation.cc",
        "src/hll/sparse_representation.cc",
        "src/hll/state.cc",
        "src/hyperloglogplusplus.cc",
    ],
    hdrs = [
        "include/zetasketch/bias_data.h",
        "include/zetasketch/core_constants.h",
        "include/zetasketch/utils/var_int.h",
        "include/zetasketch/utils/buffer_traits.h",
        "include/zetasketch/utils/iterators.h",
        "include/zetasketch/hll/state.h",
        "include/zetasketch/hll/representation.h",
        "include/zetasketch/hll/encoding.h",
        "include/zetasketch/hll/math_utils.h",
        "include/zetasketch/hll/normal_representation.h",
        "include/zetasketch/hll/sparse_representation.h",
        "include/zetasketch/hyperloglogplusplus.h",
    ],
    copts = ["-std=c++23"],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "@protobuf//:protobuf",
        "//src/proto:zetasketch_cc_proto",
    ],
)
