load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "farmhash_test",
    srcs = ["farmhash_test.cpp"],
    deps = [
        "//src/farmhash",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "proto_test",
    srcs = ["proto_test.cpp"],
    deps = [
        "//src/proto:zetasketch_cc_proto",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "buffer_writer_test",
    srcs = ["buffer_writer_test.cpp"],
    deps = [
        "//:zetasketch-cpp",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "math_utils_test",
    srcs = ["hll/math_utils_test.cpp"],
    deps = [
        "//:zetasketch-cpp",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "normal_representation_test",
    srcs = ["hll/normal_representation_test.cpp"],
    deps = [
        "//:zetasketch-cpp",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "iterators_test",
    srcs = ["iterators_test.cpp"],
    deps = [
        "//:zetasketch-cpp",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "sparse_representation_test",
    srcs = ["sparse_representation_test.cpp"],
    deps = [
        "//:zetasketch-cpp",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "state_test",
    srcs = ["state_test.cpp"],
    deps = [
        "//:zetasketch-cpp",
        "//src/proto:zetasketch_cc_proto",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "hyperloglogplusplus_test",
    srcs = ["hyperloglogplusplus_test.cpp"],
    deps = [
        "//:zetasketch-cpp",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "golden_corpus_test",
    srcs = ["golden_corpus_test.cpp"],
    data = ["golden_corpus.tsv"],
    deps = [
        "//:zetasketch-cpp",
        "@googletest//:gtest_main",
    ],
)

java_binary(
    name = "ZetaSketchCli",
    srcs = ["ZetaSketchCli.java"],
    main_class = "ZetaSketchCli",
    deps = [
        "@maven//:com_google_zetasketch_zetasketch",
    ],
)

cc_test(
    name = "differential_fuzzer",
    srcs = ["differential_fuzzer_test.cpp"],
    data = [":ZetaSketchCli"],
    args = ["--java_cli=tests/ZetaSketchCli"],
    deps = [
        "//:zetasketch-cpp",
        "@googletest//:gtest",
    ],
)

cc_test(
    name = "error_handling_test",
    srcs = ["error_handling_test.cpp"],
    deps = [
        "//:zetasketch-cpp",
        "@googletest//:gtest_main",
    ],
)

