#!/usr/bin/env python3
"""Checks that bias_data.h still holds the reference's own tables.

The header is generated by tools/generate_bias_data.py and then
formatted, so comparing it textually with a fresh run would report
formatting rather than content. This compares the numbers instead: the
precision range, the linear counting thresholds, and every mean and
bias value, against the reference implementation's Data.java.

Usage:
  tools/check_bias_data.py <path to bias_data.h> <path to Data.java>
"""

import re
import sys
from pathlib import Path


def strip_comments(text):
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.S)
    return re.sub(r"//[^\n]*", "", text)


def java_scalar(source, name):
    match = re.search(r"static final int " + name + r" = (\d+);", source)
    if match is None:
        raise SystemExit(f"cannot find {name} in the reference source")
    return int(match.group(1))


def java_rows(source, name):
    match = re.search(
        r"double\[\]\[\] " + name + r" = \{(.*?)\n  \};", source, re.S)
    if match is None:
        raise SystemExit(f"cannot find {name} in the reference source")
    out, depth, current = [], 0, ""
    for character in match.group(1):
        if character == "{":
            depth += 1
            if depth == 1:
                current = ""
                continue
        elif character == "}":
            depth -= 1
            if depth == 0:
                out.append(current)
                continue
        if depth >= 1:
            current += character
    return [[float(value) for value in re.split(r"[,\s]+", row.strip()) if value]
            for row in out]


def java_flat(source, name):
    match = re.search(r"int\[\] " + name + r" = \{(.*?)\};", source, re.S)
    if match is None:
        raise SystemExit(f"cannot find {name} in the reference source")
    return [int(value) for value in re.split(r"[,\s]+", match.group(1).strip())
            if value]


def header_arrays(source):
    """Returns each array's values and its declared extent.

    The extent matters on its own: widening an array leaves the tail
    zero filled, which moves the last mean to zero and so disables the
    correction for that precision without altering a single value the
    reference supplied.
    """
    out = {}
    pattern = r"std::array<(?:double|int32_t), (\d+)> (k\w+) = \{(.*?)\};"
    for match in re.finditer(pattern, source, re.S):
        values = [value for value in re.split(r"[,\s]+", match.group(3).strip())
                  if value]
        out[match.group(2)] = (int(match.group(1)),
                               [float(value) for value in values])
    return out


def name_values(arrays, name):
    """Returns just the values of a named array, or None if absent."""
    entry = arrays.get(name)
    return None if entry is None else entry[1]


def header_scalar(source, name):
    match = re.search(r"(?:int|int32_t) " + name + r" = (\d+);", source)
    if match is None:
        raise SystemExit(f"cannot find {name} in the header")
    return int(match.group(1))


def header_span_table(source, name):
    """Returns the array names a dispatch table lists, in order."""
    match = re.search(
        r"std::array<std::span<const double>, (\d+)> " + name + r" = \{(.*?)\};",
        source, re.S)
    if match is None:
        raise SystemExit(f"cannot find the {name} dispatch table in the header")
    return (int(match.group(1)),
            re.findall(r"std::span<const double>\((k\w+)\)", match.group(2)))


def main():
    if len(sys.argv) != 3:
        raise SystemExit(__doc__)
    header = strip_comments(Path(sys.argv[1]).read_text())
    reference = strip_comments(Path(sys.argv[2]).read_text())

    minimum = java_scalar(reference, "MINIMUM_PRECISION")
    maximum = java_scalar(reference, "MAXIMUM_PRECISION")
    failures = []

    if header_scalar(header, "kMinimumPrecision") != minimum:
        failures.append("the minimum precision differs from the reference")
    if header_scalar(header, "kMaximumPrecision") != maximum:
        failures.append("the maximum precision differs from the reference")

    if header_scalar(header, "kNumberOfNeighborsInKnn") != java_scalar(
            reference, "NUMBER_OF_NEIGHBORS_IN_KNN"):
        failures.append("the neighbour count differs from the reference")

    arrays = header_arrays(header)
    for name, (extent, values) in sorted(arrays.items()):
        if extent != len(values):
            failures.append(
                f"{name} declares room for {extent} values and holds "
                f"{len(values)}")

    thresholds = [float(value) for value in
                  java_flat(reference, "linearCountingThreshold")]
    if name_values(arrays, "kLinearCountingThreshold") != thresholds:
        failures.append("the linear counting thresholds differ")

    for prefix, name in (("kMeanData", "meanData"), ("kBiasData", "biasData")):
        rows = java_rows(reference, name)
        if len(rows) != maximum - minimum + 1:
            failures.append(f"{name} has {len(rows)} rows in the reference")
            continue
        for offset, row in enumerate(rows):
            key = f"{prefix}{offset + minimum}"
            if key not in arrays:
                failures.append(f"{key} is missing from the header")
            elif name_values(arrays, key) != row:
                failures.append(
                    f"{key} differs from the reference "
                    f"({len(name_values(arrays, key))} values against "
                    f"{len(row)})")

    # The dispatch tables decide which row each precision reads, so a
    # permutation there is as damaging as an edited value and is not
    # visible in the arrays themselves.
    for prefix in ("kMeanData", "kBiasData"):
        expected = [f"{prefix}{precision}"
                    for precision in range(minimum, maximum + 1)]
        extent, listed = header_span_table(header, prefix)
        if listed != expected:
            failures.append(
                f"the {prefix} dispatch table does not list the rows for "
                f"precisions {minimum} through {maximum} in order")
        if extent != len(expected):
            failures.append(
                f"the {prefix} dispatch table declares room for {extent} "
                f"rows and lists {len(expected)}")

    if failures:
        for failure in failures:
            print(failure, file=sys.stderr)
        raise SystemExit(1)
    print("the header holds the reference's tables for precisions "
          f"{minimum} through {maximum}")


if __name__ == "__main__":
    main()
