#!/usr/bin/env python3
"""Generates include/zetasketch/bias_data.h from the Java reference.

The HyperLogLog++ bias correction tables, the empirical linear counting
thresholds and the range of precisions they cover are all data rather
than logic, and transcribing them by hand is how they go wrong. This
script extracts them from the reference implementation's Data.java and
writes the header, preserving each literal exactly as the reference
spells it so the values cannot drift in conversion.

Usage:
  tools/generate_bias_data.py <path to Data.java> <java revision>
"""

import re
import sys
from pathlib import Path

HEADER = """// Copyright 2019 Google LLC
// Copyright 2026 RowKeyDB
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// The tables below are the empirical HyperLogLog++ bias correction
// data published by Google in the ZetaSketch project, taken verbatim
// from its Data.java at revision {revision} and licensed under the
// Apache License, Version 2.0. Generated by
// tools/generate_bias_data.py, then formatted with clang-format. Do
// not edit by hand; run the generator instead.

#ifndef ZETASKETCH_BIAS_DATA_H_
#define ZETASKETCH_BIAS_DATA_H_

#include <array>
#include <cstdint>
#include <span>

// NOLINTBEGIN
namespace zetasketch::internal {{

inline constexpr int32_t kMinimumPrecision = {minimum};
inline constexpr int32_t kMaximumPrecision = {maximum};
inline constexpr int kNumberOfNeighborsInKnn = {neighbours};
"""


def strip_comments(text):
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.S)
    return re.sub(r"//[^\n]*", "", text)


def scalar(source, name):
    match = re.search(
        r"static final int " + name + r" = (\d+);", source)
    if match is None:
        raise SystemExit(f"cannot find {name} in the reference source")
    return int(match.group(1))


def rows(source, name):
    match = re.search(
        r"double\[\]\[\] " + name + r" = \{(.*?)\n  \};", source, re.S)
    if match is None:
        raise SystemExit(f"cannot find {name} in the reference source")
    out, depth, current = [], 0, ""
    for character in match.group(1):
        if character == "{":
            depth += 1
            if depth == 1:
                current = ""
                continue
        elif character == "}":
            depth -= 1
            if depth == 0:
                out.append(current)
                continue
        if depth >= 1:
            current += character
    return [[literal for literal in re.split(r"[,\s]+", row.strip()) if literal]
            for row in out]


def flat(source, name):
    match = re.search(r"int\[\] " + name + r" = \{(.*?)\};", source, re.S)
    if match is None:
        raise SystemExit(f"cannot find {name} in the reference source")
    return [literal for literal in re.split(r"[,\s]+", match.group(1).strip())
            if literal]


def emit_array(name, kind, values):
    body = ", ".join(values)
    return (f"inline constexpr std::array<{kind}, {len(values)}> {name} = {{\n"
            f"    {body}}};\n")


def emit_spans(name, members):
    lines = [f"inline constexpr std::array<std::span<const double>, "
             f"{len(members)}> {name} = {{"]
    lines += [f"    std::span<const double>({member})," for member in members]
    lines.append("};\n")
    return "\n".join(lines)


def main():
    if len(sys.argv) != 3:
        raise SystemExit(__doc__)
    source = strip_comments(Path(sys.argv[1]).read_text())
    revision = sys.argv[2]

    minimum = scalar(source, "MINIMUM_PRECISION")
    maximum = scalar(source, "MAXIMUM_PRECISION")
    neighbours = scalar(source, "NUMBER_OF_NEIGHBORS_IN_KNN")
    means = rows(source, "meanData")
    biases = rows(source, "biasData")
    thresholds = flat(source, "linearCountingThreshold")

    span = maximum - minimum + 1
    for label, table in (("meanData", means), ("biasData", biases),
                         ("linearCountingThreshold", [thresholds])):
        count = len(table) if label != "linearCountingThreshold" else len(
            thresholds)
        if count != span:
            raise SystemExit(
                f"{label} has {count} entries, expected {span}")
    if [len(row) for row in means] != [len(row) for row in biases]:
        raise SystemExit("mean and bias rows differ in length")

    out = [HEADER.format(revision=revision, minimum=minimum, maximum=maximum,
                         neighbours=neighbours)]
    out.append("\n" + emit_array("kLinearCountingThreshold", "int32_t",
                                 thresholds))

    for prefix, table in (("kMeanData", means), ("kBiasData", biases)):
        out.append("")
        for offset, row in enumerate(table):
            out.append(emit_array(f"{prefix}{offset + minimum}", "double", row))
        out.append(emit_spans(
            prefix,
            [f"{prefix}{offset + minimum}" for offset in range(len(table))]))

    out.append("\n}  // namespace zetasketch::internal\n// NOLINTEND\n")
    out.append("\n#endif  // ZETASKETCH_BIAS_DATA_H_\n")
    sys.stdout.write("\n".join(out))


if __name__ == "__main__":
    main()
